apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      name: frontend-service
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: milospp/windbnb-frontend
          imagePullPolicy: Always
      restartPolicy: Always
