apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service-lb
spec:
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 80
  type: LoadBalancer
